package prueba;
import java.sql.SQLException;
import java.sql.ResultSet;

import modelo.Operacion;

public class Principal {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		/*
		Operacion op = new Operacion();
		ResultSet rs= null;
		try {
			//rs= op.listaEmployeeID();
			//op.actualizaSueldoEmpleado(100, 30000);
			//System.out.println("Actualizacion realizada");
			System.out.println("Listado");
			while (rs.next()) {
				System.out.println(rs.getInt("employee_id"));
				
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			//e.printStackTrace();
			System.out.println("Error: " + e.toString());
		} */

	}

}
